config/routes.rb
Rails.application.routes.draw do
  resources 'currencies'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_variables  
  def new
    @symbols = load_symbols
  end
  
  def create
    @from = params[:from]
    @to = params[:to]
    @amount = params[:amount]
    res = @conn.post "#/convert/#{@amount}/#{@from}/#{@to}?app_id=#{@app_id}"
    byebug
  end

  private

  def set_variables
    @base_url = 'https://openexchangerates.org/api/'
    @app_id = 'bfcb324948644df1ae81d3ca5161e47b'
    @conn = Faraday.new(url: @base_url)
  end

  def load_symbols
    res = @conn.get "codes/dbc95df78e2018213cb653c0"
    hash = JSON.parse(res.body)
    hash
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/currencies/new.html.erb
<h3>Conversor de moédas</h3>
<%= form_tag(currencies_path, method: :post) do %>
  <%= label_tag "Valor:" %>
  <%= text_field_tag "amount" %>

  <%= label_tag "Converter de:" %>
  <select name="from">
    <% @symbols.each do |s| %>
      <option value="<%= s[0] %>"><%= s[0] %> - <%= s[1] %></option>
    <% end %>
  </select>

  <%= label_tag "Para:" %>
  <select name="to">
    <% @symbols.each do |s| %>
      <option value="<%= s[0] %>"><%= s[0] %> - <%= s[1] %></option>
    <% end %>
  </select>

  <%= submit_tag "Converter" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConversorMoedas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>